### ISSUE TITLE
CreateZFSVolume does not respect fsType=zfs -> dataset

### ISSUE THREAD

**Issue by cruwe** [openebs/zfs-localpv#143]
**What steps did you take and what happened:**
With storageclass
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-dataset
allowVolumeExpansion: true
parameters:
  fsType: "zfs"
provisioner: zfs.csi.openebs.io
```
the created datasets end up with type volume.

**What did you expect to happen:**

With fsType set, I'd like to have a dataset.

**Anything else you would like to add:**
The parameter `req.GetParameters()["fstype"]` in `func CreateZFSVolume(req *csi.CreateVolumeRequest) (string, error)` is inconsistent with the CRD. Either it is fstype in the CRD or it is `req.GetParameters()["fsType"]`.
