### ISSUE TITLE
Support R[OW]X for dataset

### ISSUE THREAD

**Issue by stevefan1999-personal** [openebs/zfs-localpv#152]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]
I cannot mount ZFS dataset to multiple pods, thus for some reason I cannot run multiple game servers using Agones, because I want to re-use the same volume to say e.g. run multiple instances of the game server with same set of plugin like Retake, TTT and such.

My current workaround is to generate multiple snapshots and let each future instance take the snapshot as cloned PVC and stick it from then on.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Allow ZFS dataset to be R[OW]X, and also state this exception in the document.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The reason to allow dataset only is that it's not an exclusive block device. Obviously, ZVOL are still forbidden.

I know there could have had Read-Write conflicts, but then I think how could people run things off NFS so nice all this years? They obviously have designed their application to have conflict-avoidance. 

Similarly, we should also state that this is dangerous and requires application change to accommodate this.

**Comment by pawanpraka1** [comment]
@stevefan1999-personal thanks for this issue. Right now we support ReadWriteOnce capability. We have a plan to support ReadWriteMany. Thanks for raising this issue. 

I see that you are already using ZFS-LocalPV for your use case. Would you like to add your use case in our ADOPTERS.md file. It will help us out when working with CNCF.

 https://github.com/openebs/openebs/issues/2719.

**Comment by pawanpraka1** [comment]
hey @stevefan1999-personal thanks, I see, you have put the comment in the Adopters.md file.
Could you also specify which localpv storage engines you are using? OpenEBS-Device, OpenEBS-Hostpath or ZFS-LocalPV? Thanks for taking time and adding your use case in the ADOPTERS.md file, appreciate it.
https://github.com/openebs/openebs/issues/2719#issuecomment-641343028

**Comment by stevefan1999-personal** [comment]
Hmm...if I take a step back and use NFS server provisioner, as suggested by the OpenEBS documents then I can have it working quite well...but I'm still interested on a solution without this kind of overhead, especially consider that Grafana can eat a lot of memory.

**Comment by stevefan1999-personal** [comment]
Implementing this could be a nice incentive for #69

**Comment by pawanpraka1** [comment]
@stevefan1999-personal there is already a PR from the community to add that feature(#69) https://github.com/openebs/zfs-localpv/pull/139.

**Comment by pawanpraka1** [comment]
Have raise a PR to add this support https://github.com/openebs/zfs-localpv/pull/164.

**Comment by pawanpraka1** [comment]
@stevefan1999-personal we have added support to allow application to share the volume via https://github.com/openebs/zfs-localpv/pull/164. Can you deploy the ci image and try the below storage class

```
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: openebs-zfspv
    parameters:
      shared: "yes"
      fstype: "zfs"
      poolname: "zfspv-pool"
    provisioner: zfs.csi.openebs.io
```

**Comment by stevefan1999-personal** [comment]
@pawanpraka1 nope.

BTW this is my final storage class config:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-local-zfs-testing-shared
parameters:
  shared: "yes"
  fstype: "zfs"
  compression: "on"
  dedup: "off"
  poolname: "rpool/k3s/openebs/testing-shared"
  recordsize: 4k
provisioner: zfs.csi.openebs.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
```

This is my PVC generated from Helm, trimmed to keep most of the reproducible information:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zero-agones-csgo
  namespace: agones-public
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 32Gi
  phase: Bound
```
But this doesn't work on a second pod I manually scheduled to replicate on, `kubectl describe` shows this:
```
Normal   Scheduled    <unknown>            default-scheduler  Successfully assigned agones-public/zero-agones-csgo-qfnzv-6rflb to serv
  Warning  FailedMount  80s                  kubelet, serv      Unable to attach or mount volumes: unmounted volumes=[base-data], unattached volumes=[base-data agones-sdk-token-px6ln empty]: timed out waiting for the condition
  Warning  FailedMount  75s (x9 over 3m23s)  kubelet, serv      MountVolume.SetUp failed for volume "pvc-af9ba9bc-ad99-4506-9c01-c3c3d2875c98" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Internal desc = rpc error: code = Internal desc = dataset can not be mounted
```
I have upgraded the CSI provisoner to CI that I reapplied again so it is indeed the latest version I think.

So yeah, no.

**Comment by pawanpraka1** [comment]
Can you paste the full log of the zfs driver?

**Comment by stevefan1999-personal** [comment]
@pawanpraka1 Oh, you're right. I see that my zfs-node pod is still 34 days ago. So I had to go full on wipe with that

**Comment by pawanpraka1** [comment]
is it working @stevefan1999-personal. Let me know if you need any help.

**Comment by stevefan1999-personal** [comment]
@pawanpraka1 well I patched my Stateful & Daemon set of zfs-localpv for all the pods's imagePullPolicy from IfNotPresent to Always, and they are supposedly re-pulled to use the latest version. However, I still can't get it to work as there's an error message "Internal desc = rpc error: code = Internal desc = verifyMount: device already mounted at [...]". This means I may have to re-create the storage class to get the "sharing" option applied. I will check out if this theory works later.

**Comment by pawanpraka1** [comment]
@stevefan1999-personal , yes volume should be provisioned with the storageclass with shared=yes parameter. You can verify that with kubectl get zv <pv name> -n openebs -oyaml, it should have shared option as yes.

**Comment by stevefan1999-personal** [comment]
@pawanpraka1 after recreating a new PVC, success!

**Comment by pawanpraka1** [comment]
since it is localpv solution and all the pods sharing the same volume will come to the same node only and kernel is still shared, so it will work for zvol also. Good to metion in both the cases applications needs to have o have conflict-avoidance mechanism.

**Comment by rudolfbyker** [comment]
Is this documented somewhere? The README still seems to suggest that only ReadWriteOnce is supported.

**Comment by pawanpraka1** [comment]
@rudolfbyker it supports ReadWriteOnce only, but you can make multiple pods use the same pvc via shared mount setting in the storageclass. See this https://github.com/openebs/zfs-localpv/blob/develop/docs/storageclasses.md#storageclass-for-sharing-the-persistence-volumes.

**Comment by rudolfbyker** [comment]
Ah, sorry. I got confused between `ReadWriteOncePod` and `ReadWriteOnce`. https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

**Comment by etlfg** [comment]
Sorry to bother and reopen this issue. I've been reading all the issues and docs I can about sharing a dataset between pods.
-  https://github.com/openebs/zfs-localpv/pull/164
- https://github.com/openebs/zfs-localpv/blob/develop/docs/storageclasses.md#storageclass-for-sharing-the-persistence-volumes
- And [here](https://github.com/openebs/zfs-localpv/issues/152) 

zfs-driver is 2.4.0

But I can't get out of `MountVolume.SetUp failed for volume "consume-pv" : rpc error: code = Internal desc = rpc error: code = Internal desc = verifyMount: device already mounted at [/var/lib/k0s/kubelet/pods/7f3fc9cd-5e94-4d32-9e59-3ae0caa41fc4/volumes/kubernetes.io~csi/import-pv/mount /host/var/lib/k0s/kubelet/pods/7f3fc9cd-5e94-4d32-9e59-3ae0caa41fc4/volumes/kubernetes.io~csi/import-pv/mount]`

I don't get either the shared-yes param in my ZFSVolume as stated [here](https://github.com/openebs/zfs-localpv/issues/152#issuecomment-653511445) 

Here are my curated resources :

```
kubectl get sc -n openebs zfs-import -o yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-import
parameters:
  compression: "off"
  dedup: "off"
  fstype: zfs
  poolname: data/import
  recordsize: 16k
  shared: "yes"
  thinprovision: "no"
provisioner: zfs.csi.openebs.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
```

```
kubectl zv -n openebs import -o yaml
apiVersion: zfs.openebs.io/v1
kind: ZFSVolume
metadata:
  name: import
  namespace: openebs
spec:
  capacity: "1073741824000"
  fsType: zfs
  ownerNodeID: main
  poolName: data
  volumeType: DATASET
status:
  state: Ready
```

```
apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: import-pv
spec:
  accessModes:
  - ReadWriteOnce # Tried ReadWriteMany just in case, doesn't work as expected
  capacity:
    storage: 1Ti
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: import-pvc
    namespace: default
  csi:
    driver: zfs.csi.openebs.io
    fsType: zfs
    volumeAttributes:
      openebs.io/poolname: data
    volumeHandle: import
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - main
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zfs-import
  volumeMode: Filesystem
status:
  phase: Bound
```

```
kubectl get pvc import-pvc -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: import-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: zfs-import
  volumeMode: Filesystem
  volumeName: import-pv
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Ti
  phase: Bound
```

Thanks in advance for providing me any clue about this..
