### ISSUE TITLE
Unable to resize block device volume

### ISSUE THREAD

**Issue by coboluxx** [openebs/zfs-localpv#280]
The openebs-zf-plugin tries a resizefs on a volumeMode=Block volume which fails obviously.

**What steps did you take and what happened:**

Create a StorageClass like:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-blk-ssd
allowVolumeExpansion: true
parameters:
  poolname: "ssd-pool"
provisioner: zfs.csi.openebs.io
volumeBindingMode: WaitForFirstConsumer
```

Create a PVC with:
```
        accessModes:
        - ReadWriteMany
        volumeMode: Block
        resources:
          requests:
            storage: 10G
        storageClassName: local-blk-hdd
```

Try to resize this volume
kubectl patch pvc test-pvc --patch='{"spec":{"resources":{"requests":{"storage":"20G"}}}}'

**What did you expect to happen:**
Volume resized.

**The output of the following commands will help us better understand what's going on**:

Output from: kubectl -n kube-system logs pod/openebs-zfs-node-56vtm openebs-zfs-plugin

I0131 18:34:50.598765       1 grpc.go:72] GRPC call: /csi.v1.Node/NodeExpandVolume requests {"capacity_range":{"required_bytes":300647710720},"volume_id":"pvc-a1e350b6-6b6c-44a7-aa07-c716cba8a5f2","volume_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-a1e350b6-6b6c-44a7-aa07-c716cba8a5f2/0145ebf4-b0d4-4bb7-9049-ea9743cb7b9a"}
E0131 18:34:50.676305       1 resize.go:33] zfspv: ResizeExtn failed error: resize2fs 1.44.1 (24-Mar-2018)
resize2fs: Bad magic number in super-block while trying to open /dev/zd64
Couldn't find valid filesystem superblock.
