### ISSUE TITLE
Owner for mounted volume is always root with no write for group and world.

### ISSUE THREAD

**Issue by Daniel-Nashed** [openebs/zfs-localpv#358]
Looks like there is no way to change that. 
So applications not running as root cannot write to this mount.

Is there any way to change the permissions to let group/world also to read it?

Example:
```
drwxr-xr-x.   3 root root 4096 Jul 13 18:42 local
```
I have installed the latest version on Ubuntu 20.10 LTS with MicroK8s and also on CentOS Stream 8 with latest k3s with the same results. And I did not find any way to work-around it beside using an init container patching the permissions or owner.

Thanks for any tip!
If this is a limitation, this would be very helpful to be resolved!

Daniel

**Comment by pawanpraka1** [comment]
@Daniel-Nashed you can use fsgroupPolocy to set the permission for the applications. See this discussion https://github.com/openebs/zfs-localpv/issues/282. You need k8s 1.20+ for this.

**Comment by Daniel-Nashed** [comment]
Thanks for your quick reply!

I checked my driver and I am running on K8s version v1.21.2.
So all the functionality should be there.

My CSI driver has set

```
  fsGroupPolicy: ReadWriteOnceWithFSType
```

And when you try to change it to `None` or any other value I get the error that this is an invalid value.

I also tried to use the following two in the `securityContext` of the pod. Both are also reported as invalid when you try to run it.
That's kind of weird.

So according to the documentation I should be able to set the driver to `None` and should be also able to use `fsGroup` settings.
I tried them with different combinations `fsGroup` alone already returns an error when creating the pod.

So according to documentation this should work. Not sure what I doing wrong here.

```
    securityContext:
      capabilities:
        add: ["SYS_PTRACE"]
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
```

Here is the error returned:

```
error: error validating "domino_test.yml": error validating data: [ValidationError(Pod.spec.containers[0].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext, ValidationError(Pod.spec.containers[0].securityContext): unknown field "fsGroupChangePolicy" in io.k8s.api.core.v1.SecurityContext]; if you choose to ignore these errors, turn validation off with --validate=false
```

Settings for the CSI driver:

```

apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"CSIDriver","metadata":{"annotations":{},"name":"zfs.csi.openebs.io"},"spec":{"attachRequired":false,"podInfoOnMount":false}}
  creationTimestamp: "2021-07-13T15:47:22Z"
  name: zfs.csi.openebs.io
  resourceVersion: "86498"
  uid: 91cd18c0-3f06-48ab-9954-66804f4cf6cc
spec:
  attachRequired: false
  fsGroupPolicy: ReadWriteOnceWithFSType
  podInfoOnMount: false
  requiresRepublish: false
  storageCapacity: false
  volumeLifecycleModes:
  - Persistent
```

See: [Reference for the volume permissions](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods)

**Comment by pawanpraka1** [comment]
@Daniel-Nashed you don't need to change the CSI driver setting. The default fsGroupPolicy is ReadWriteOnceWithFSType. Can you try the security-context-demo.yaml.txt mentioned in the issue https://github.com/openebs/zfs-localpv/issues/282. Seems to be some issue the yaml you are using.

**Comment by Daniel-Nashed** [comment]
Thanks, tried it an I cannot write into `/demo` .  
The ultimate goal here is to change the permissions to 777 for the mount.
It would be also OK if the user can write specifying `fsGroup`. In my test with the demo it did not show any difference.

```
 id
uid=1000 gid=2000 groups=2000
/ $ cd /data
/data $ mkdir test
mkdir: can't create directory 'test': Permission denied
```

**Comment by mittachaitu** [comment]
> error: error validating "domino_test.yml": error validating data: [ValidationError(Pod.spec.containers[0].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext, ValidationError(Pod.spec.containers[0].securityContext): unknown field "fsGroupChangePolicy" in io.k8s.api.core.v1.SecurityContext]; if you choose to ignore these errors, turn validation off with --validate=false

This is causing due to specifying `fsGroupChangePolicy` & `fsGroup` under `container.securityContext` but it should be at pod level security context(since same volume is shared across containers in same pod). For example:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: fio
spec:
  restartPolicy: Never
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
  containers:
  - name: perfrunner
    image: openebs/tests-fio
    securityContext:
      capabilities:
        add: ["SYS_PTRACE"]
      runAsNonRoot: true
      runAsUser: 1000
...
...
...    
```
