### ISSUE TITLE
volumesnapshot restoreSize is not set when returning from createSnapshot response

### ISSUE THREAD

**Issue by chinglinwen** [openebs/zfs-localpv#416]
**What steps did you take and what happened:**

create volumesnapshot, cause later create PVC(which source is snapshot) failed ( because of zero storage.size )

```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  labels:
  name: vm-fedora
  namespace: default
spec:
  source:
    pvc:
      name: fedora34-openebs-zfspvx
      namespace: default
  storage:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 6Gi
    storageClassName: openebs-zfspv
    volumeMode: Block
```

```
[root@hcit3 ~]# kubectl get vs
NAME        READYTOUSE   SOURCEPVC                 SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS   SNAPSHOTCONTENT                                    CREATIONTIME   AGE
vm-fedora   true         fedora34-openebs-zfspvx                           0             openebs-zfspv   snapcontent-fcb70074-a69e-4618-8668-30dfbace6830   74s            74s
[root@hcit3 ~]# kubectl get vsc
NAME                                               READYTOUSE   RESTORESIZE   DELETIONPOLICY   DRIVER               VOLUMESNAPSHOTCLASS   VOLUMESNAPSHOT   VOLUMESNAPSHOTNAMESPACE   AGE
snapcontent-fcb70074-a69e-4618-8668-30dfbace6830   true         0             Delete           zfs.csi.openebs.io   openebs-zfspv         vm-fedora        default                   116s
```

```
1.654678004992305e+09   ERROR   controller.smartclone-controller        error creating pvc from snapshot        {"VolumeSnapshot/PersistentVolumeClaim": "default/vm-fedora", "error": "PersistentVolumeClaim \"vm-fedora\" is invalid: spec.resources[storage]: Invalid value: \"0\": must be greater than zero"}
```

**What did you expect to happen:**

restoresize should have been set
```
kubectl get vs,vsc
```

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other [Pastebin](https://pastebin.com/) is fine.)

* `kubectl logs -f openebs-zfs-controller-0 -n kube-system -c openebs-zfs-plugin`
* `kubectl logs -f openebs-zfs-node-[xxxx] -n kube-system -c openebs-zfs-plugin`
* `kubectl get pods -n kube-system`
* `kubectl get zv -A -o yaml`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- ZFS-LocalPV version:  v2.1.0
- Kubernetes version (use `kubectl version`): 1.23.5
- Kubernetes installer & version: 
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): centos 8.4.2105
