### ISSUE TITLE
Can't clone PVC that is from an encrypted storage-class

### ISSUE THREAD

**Issue by mattlqx** [openebs/zfs-localpv#427]
**What steps did you take and what happened:**

I created a StorageClass that has encryption enabled via parameters.

```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-kubevirt
parameters:
  recordsize: "256k"
  compression: "on"
  dedup: "on"
  fstype: "zfs"
  encryption: aes-256-gcm
  poolname: "bigraid/encrypted/kubevirt"
allowVolumeExpansion: true
provisioner: zfs.csi.openebs.io
```

A PVC was created with that StorageClass and it does have encryption enabled:

```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vmi-ubuntu-jammy-amd64
  namespace: vm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "56811736720"
  storageClassName: zfs-kubevirt
```

```
bigraid/encrypted/kubevirt/pvc-21874f08-9638-4c5c-8450-b58afa230060  encryption            aes-256-gcm            -
```

But creating a PVC with that PVC as the source gives an error that `encryption` is read-only.

```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-test-data
  namespace: vm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: zfs-kubevirt
  resources:
    requests:
      storage: 53Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: vmi-ubuntu-jammy-amd64
```

**What did you expect to happen:**

I expected a new PVC with `dataSource` 

**The output of the following commands will help us better understand what's going on**:
```
openebs-zfs-plugin I1028 01:03:20.650749       1 zfs_util.go:450] creating snapshot pvc-21874f08-9638-4c5c-8450-b58afa230060@pvc-0b04b9fe-c2e1-4d6f-adf8-b56deee375a3 for the clone bigraid/encrypted/kubev
irt/pvc-0b04b9fe-c2e1-4d6f-adf8-b56deee375a3                                                                                                                                                               
openebs-zfs-plugin I1028 01:03:20.678614       1 zfs_util.go:684] snapshot already there bigraid/encrypted/kubevirt/pvc-21874f08-9638-4c5c-8450-b58afa230060@pvc-0b04b9fe-c2e1-4d6f-adf8-b56deee375a3      
openebs-zfs-plugin E1028 01:03:20.716757       1 zfs_util.go:468] zfs: could not clone volume bigraid/encrypted/kubevirt/pvc-0b04b9fe-c2e1-4d6f-adf8-b56deee375a3 cmd [clone -o quota=56908316672 -o record
size=256k -o mountpoint=legacy -o dedup=on -o compression=on -o encryption=aes-256-gcm bigraid/encrypted/kubevirt/pvc-21874f08-9638-4c5c-8450-b58afa230060@pvc-0b04b9fe-c2e1-4d6f-adf8-b56deee375a3 bigraid
/encrypted/kubevirt/pvc-0b04b9fe-c2e1-4d6f-adf8-b56deee375a3] error: cannot create 'bigraid/encrypted/kubevirt/pvc-0b04b9fe-c2e1-4d6f-adf8-b56deee375a3': 'encryption' is readonly                         
openebs-zfs-plugin I1028 01:03:20.774675       1 volume.go:254] Successfully synced 'openebs/pvc-0b04b9fe-c2e1-4d6f-adf8-b56deee375a3'   
```

**Environment:**
- ZFS-LocalPV version: 2.1.0
- Kubernetes version (use `kubectl version`): 1.24.6
- Kubernetes installer & version: Kubespray 1.20.0
- Cloud provider or hardware configuration: bare-metal
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04
