### ISSUE TITLE
How can i resize a volume with "VolumeMode: Block"

### ISSUE THREAD

**Issue by use-epoll** [openebs/zfs-localpv#436]
**Describe the problem/challenge you have**
I have a single node k8s cluster for creating kvm virtual machines:
kubernetes： v1.24.7
containerd: 1.6.12
kubevirt: v.0.54.0

**Describe the solution you'd like**
I imported a raw image of Ubuntu, but when I used that image to create a virtual machine, the created block volume could not be created because the created system disk needs to be resized but does not need to be formatted directly, so zfs-localpv does not seem to handle resize directly

**Anything else you would like to add:**
I need rezise directly possible even for block

**Comment by use-epoll** [comment]
when i resize a  pv  which volumeMode is 'block' and created from a snapshot  (need resize to 40G)
the csi-resizer reback "'FileSystemResizeRequired' Require file system resize of volume on node"
PS:  the original volume of the snapshot is also a 'block' volume  but size is 6G 

sc.yaml
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: openebs-zfsblock
  annotations:
    storageclass.kubernetes.io/allow-clone: 'true'
    storageclass.kubernetes.io/allow-snapshot: 'true'
provisioner: zfs.csi.openebs.io
parameters:
  poolname: zfspool
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
```
