### ISSUE TITLE
Erroneous release v2.4.1

### ISSUE THREAD

**Issue by aasseman** [openebs/zfs-localpv#503]
- The Helm files point to container image `openebs/zfs-driver:2.4.0` instead of `openebs/zfs-driver:2.4.1`
- Container image `openebs/zfs-driver:2.4.1` isn't even published.

I was hoping to get the https://github.com/openebs/zfs-localpv/pull/451 fix, but since the latest Helm release still points to the older code it's not.

**Comment by jnels124** [comment]
@aasseman I have worked around this by publishing my own image based off the 2.4.1 tag. You can use that image if you wish:

  ```
zfsPlugin:
    image:
      registry: gcr.io/
      repository: mirrornode/zfs-driver
      pullPolicy: IfNotPresent
      tag: 2.4.1-HEDERA
```
Depending on your cluster setup, you may also need to add.

 ```
 crd:
    volumeSnapshot: false
```
