### ISSUE TITLE
No clear default value for thin provisioning of filesystems

### ISSUE THREAD

**Issue by abuisine** [openebs/zfs-localpv#560]
**What steps did you take and what happened:**
I created a simple storageClass as follows :
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: openebs-zfspv
allowVolumeExpansion: true
parameters:
 recordsize: "128k"
 fstype: "zfs"
 poolname: "zfspv-pool"
provisioner: zfs.csi.openebs.io
```
and then created both a PVC and a Pod in order to trigger the CSI provisioner which then creates a zfs FS

**What did you expect to happen:**
I would have expected a thick provisioning aka reservation or refreservation property on the created zfs FS but I got none.

As there is no default value in the documentation : https://github.com/openebs/zfs-localpv/blob/develop/docs/storageclasses.md#thinprovision-optional-parameter,
I had a look at the code and there is, it seems, a `no` default value : https://github.com/openebs/zfs-localpv/blob/1c4a810e5302c7b4a176ca109f9e11bd5fd6d8a9/pkg/apis/openebs.io/zfs/v1alpha1/zfsvolume.go#L151

**The output of the following commands will help us better understand what's going on**:
```
zfs list -o name,quota,refreserv,reserv
NAME                                                 QUOTA  REFRESERV  RESERV
zfspv-pool                                            none       none    none
zfspv-pool/pvc-b16e1228-ff11-4101-a117-01f65ce3257e    21G       none    none
```

**Anything else you would like to add:**
I would suggest :
- to remove the comment in the code as there is actually no default behavior within this CSI provisioner
- add in the documentation an information about the default behavior of ZFS (which is thinprovision: yes, at least in my setup)

Also it is worth to be noted that setting `thinprovision: "no"` works as expected, my problem is limited to the default behavior.

**Environment:**
- LocalPV-ZFS version:  zfs-localpv-2.4.0
- Kubernetes version (use `kubectl version`): v1.27.12
- Kubernetes installer & version: v1.27.12+rke2r1
- Cloud provider or hardware configuration: VM on ProxmoxVE
- OS (e.g. from `/etc/os-release`): Flatcar 3815.2.0
