### ISSUE TITLE
The `quota` property missing when restoring from snapshot (zfs-localpv 2.7.1)

### ISSUE THREAD

**Issue by mfhunruh** [openebs/zfs-localpv#641]
**What steps did you take and what happened:**
1. create a ZFS volume and PV:
```
---
apiVersion: zfs.openebs.io/v1
kind: ZFSVolume
metadata:
  name: my-zfs-volume
  namespace: controller-openebs
spec:
  capacity: "10737418240"
  fsType: zfs
  ownerNodeID: my-node
  poolName: tank
  volumeType: DATASET
  shared: "yes"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-zfs-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: my-zfs-volume
    namespace: default
  csi:
    driver: zfs.csi.openebs.io
    fsType: zfs
    volumeAttributes:
      openebs.io/poolname: tank
    volumeHandle: my-zfs-volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - my-node
  persistentVolumeReclaimPolicy: Retain
  storageClassName: openebs-zfspv
  volumeMode: Filesystem
```
2. create a deployment with PVC, write some data on volume
3. create backup via velero with openebs-plugin (3.6.0): ```velero backup create my-test-backup --snapshot-volumes --volume-snapshot-locations=my-snapshots```
4. scale the deployment, remove pvc and pv;
5. restore from backup: ```velero restore create --from-backup my-test-backup --restore-volumes=true```

**What did you expect to happen:**

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other [Pastebin](https://pastebin.com/) is fine.)

```
$ velero restore describe my-test-backup-20250301231613
<...>
Errors:
  Velero:     <none>
  Cluster:  error executing PVAction for persistentvolumes/my-zfs-volume: rpc error: code = Unknown desc = zfs: error in restoring my-zfs-volume.my-test-backup, status:{Failed}
  Namespaces: <none>
<...>
```

```
$ kubectl -n controller-openebs logs openebs-zfs-localpv-node-htxtr openebs-zfs-plugin
E0301 20:16:14.597754       1 zfs_util.go:894] zfs: could not restore the volume tank/my-zfs-volume cmd [-c nc -w 3 192.168.64.131 9010 | zfs recv -o =10737418240 -o mountpoint=legacy -F tank/my-zfs-volume] error: cannot receive: cannot receive: invalid property ''
E0301 20:16:14.597770       1 restore.go:88] restore my-zfs-volume.my-test-backup failed my-zfs-volume err exit status 1
```

```
kubectl get zfsvol -A
NAMESPACE            NAME                                           ZPOOL   NODEID             SIZE           STATUS   FILESYSTEM   AGE
controller-openebs   my-zfs-volume                                  tank    my-zfs-node        10737418240    Ready    zfs          46m
```

**Environment:**
- LocalPV-ZFS version: 2.7.1
- Kubernetes version (use `kubectl version`): v1.30.3
- Kubernetes installer & version: N/A
- Cloud provider or hardware configuration: Bare metal
- OS (e.g. from `/etc/os-release`): Talos Linux 1.9.4
