### ISSUE TITLE
Question: Design choice to always create a zfs dataset of type "volume"?

### ISSUE THREAD

**Issue by dionysius** [openebs/zfs-localpv#648]
While evaluating zfs-localpv I encountered an unexpected behaviour. It seems it always creates a zfs dataset of type volume (block-storage) even when the PVC is defined to request a filesystem. Thus [csi-provisioner](https://github.com/kubernetes-csi/external-provisioner) seems to be needed to turn the volume into a filesystem as a next "layer". Isn't this overcomplicated, error prone and possibly with a bit of runtime overhead instead managing the zfs volume as type filesystem directly in zfs? Unfamiliar with CSI, but this sounds to me that this way we could then also skip side-containers `csi-provisioner` and `csi-resizer`. Any insights?

Example/Reference setup according to the quick-start guide with some tweaks:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local
parameters:
  compression: "on"
  dedup: "on"
  fstype: ext4
  poolname: local
  volblocksize: 4k
provisioner: zfs.csi.openebs.io
reclaimPolicy: Delete
```
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pv-5
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local
  volumeMode: Filesystem
```

Results:
```bash
# zfs list -o name,type,used,avail,refer,quota,refquota,reservation,refreservation,mountpoint,mounted,ratio local -r
NAME                                                TYPE         USED  AVAIL     REFER  QUOTA  REFQUOTA  RESERV  REFRESERV  MOUNTPOINT  MOUNTED  RATIO
local                                               filesystem   322M   510M       24K   none      none    none       none  /local      yes      1.45x
local/pvc-9079d45d-2b3c-4aa5-8002-25720d5536f6      volume       108M   618M       27K      -         -    none       108M  -           -        4.20x
```

Expected:
`local/pvc-9079d45d-2b3c-4aa5-8002-25720d5536f6` is of type filesystem

Additionally the [CSI interface](https://github.com/container-storage-interface/spec/blob/master/csi.proto#L370) seems to indicate whether a requested volume should be block-storage or a filesystem by setting the field `volume_capabilities` to either [BlockVolume](https://github.com/container-storage-interface/spec/blob/master/csi.proto#L448) or [MountVolume](https://github.com/container-storage-interface/spec/blob/master/csi.proto#L453), no?
